apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
  namespace: microservices
data:
  USER_SERVICE_URL: "http://user-service:8080"
  ORDER_SERVICE_URL: "http://order-service:8080"
  PAYMENT_SERVICE_URL: "http://payment-service:8080"
