apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: microservices
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "postgres"
  SECURITY_JWT_SECRET: "619296d21b477d598dc0dc0ec8eec349"
